/** Declaration file generated by dts-gen */
import {
  Action,
  Service,
} from 'moleculer';

export default class DBService extends Service {
  actions: {
    count: Action
  };
}

export type MoleculerDbListResult<T> = {
  rows: Array<T>
  total: number,
  page: number,
  pageSize: number,
  totalPages: number
};

export type MoleculerDbFindResult<T> = Array<T>;

declare module 'moleculer-db';
